sensor_kit_base_link:
  lidar_fl_base_link:
    x: 1.1249421160358644
    y: 0.89340555668607669
    z: -0.4484982863297608
    roll: -3.135928690457725
    pitch: -0.012965987882825145
    yaw: 1.1365750414117932
  lidar_fr_base_link:
    x: 1.1611294806798593
    y: -0.88174876332997476
    z: -0.48219219180671852
    roll: 0.0061551395959417486
    pitch: 3.1285480929847043
    yaw: 2.0409376811576481
  lidar_ft_base_link:
    x: 0.88063984267747719
    y: 0.0099999992991057964
    z: -0.083437850723266913
    roll: 0.013525612196624973
    pitch: 0.013851385130191242
    yaw: 0.01151549695348783
  lidar_rear_base_link:
    x: -1.9595356818869363
    y: -0.026865243459528607
    z: -1.5161449950698445
    roll: -0.016084272699686913
    pitch: -3.0781455814759471
    yaw: 0.023126610460442169
  lidar_rt_base_link:
    x: -0.92178826491305532
    y: -0.019744004415643099
    z: -0.0028000544525950133
    roll: 3.1276908690255549
    pitch: 3.1170512226174871
    yaw: 0.037766046333846642
  gnss_link:
    x: -1.10
    y: 0.15
    z: -1.50
    roll: 0.0
    pitch: 0.0
    yaw: -0.01
  camera0/camera_link:
    x: 0.92308663337009411
    y: -0.084238313871196097
    z: 0.47353795629360712
    roll: -1.5309821207762995
    pitch: -0.0047230708657444165
    yaw: -1.6373760384774567
  camera1/camera_link:
    x: -0.092483767696104391
    y: -1.159167159786908
    z: -1.799885658539627
    roll: 1.3088214647530829
    pitch: -1.5330696887188751
    yaw: 0.25227949260398463
  camera2/camera_link:
    x: 0.034768465326013187
    y: -1.2190681742197698
    z: -1.8478205438403981
    roll: -0.64127218608905345
    pitch: 1.5405264882148721
    yaw: -2.208520560655586
  camera3/camera_link:
    x: 1.0166803675862521
    y: 0.95239974997625831
    z: -0.44682014709151563
    roll: -1.8741233021754418
    pitch: -0.015286878023428816
    yaw: 0.88671948806793266
  camera4/camera_link:
    x: 1.3655306317891982
    y: -0.54730869415652317
    z: 0.0064146681874275302
    roll: -2.0102340545479431
    pitch: 0.77004711472601128
    yaw: 2.8317332506720758
  camera5/camera_link:
    x: 1.3880583177242583
    y: -0.61494612792636649
    z: -0.043867051921932187
    roll: 1.9672045462126464
    pitch: -0.75655893391532447
    yaw: -0.28946861462858881
  camera6/camera_link:
    x: -1.4208573608314297
    y: -0.54990184462988245
    z: 0.031233772964919915
    roll: -2.0218885637384676
    pitch: -0.79596486370831465
    yaw: -2.8165947095150741
  camera7/camera_link:
    x: 0.708
    y: 1.053
    z: 1.479
    roll: -1.553
    pitch: 0.063
    yaw: -1.584