map:
  lidar_fl_base_link:
    x: 2.41714
    y: -0.261178
    z: 1.36835
    roll: -3.12997
    pitch: -0.0053305399999999
    yaw: 1.12304
  lidar_fr_base_link:
    x: 2.39317
    y: -1.98624
    z: 1.36147
    roll: 3.130599653589793
    pitch: 0.0068426535897934
    yaw: -1.1088626535897934
  lidar_ft_base_link:
    x: 2.12169
    y: -1.09683
    z: 1.71922
    roll: 0.00642365
    pitch: 0.0218040000000002
    yaw: 0.00396763
  lidar_rt_base_link:
    x: 0.364018
    y: -1.07165
    z: 1.82745
    roll: 0.0006726535897933
    pitch: -0.0125626535897929
    yaw: -3.123166453589793
  lidar_rear_base_link:
    x: -0.679199
    y: -1.01732
    z: 0.373472
    roll: -3.1415816145897932
    pitch: -0.0823126535897929
    yaw: -3.121929353589793
