sensor_kit_base_link:
  lidar_fl_base_link:
    x: 1.1021753463745116
    y: 0.928
    z: -0.5404953193664551
    roll: 3.136828464553929
    pitch: -6.472783168312924e-05
    yaw: 1.1337889049066634
  lidar_fr_base_link:
    x: 1.147
    y: -0.905
    z: -0.560504680633545
    roll: -0.009991820046960264
    pitch: -3.1374875737370207
    yaw: 2.0155832101653326
  lidar_ft_base_link:
    x: 0.8625719451904297
    y: 0
    z: 0.014833389282226562
    roll: 0.013750506459994772
    pitch: 0.02697466808122232
    yaw: -0.0029244125951245342
  lidar_rear_base_link:
    x: -1.9546276626586914
    y: 0
    z: -1.6165663414001465
    roll: 3.1315350164200106
    pitch: -0.02391871712452
    yaw: 3.1463238657301913
  lidar_rt_base_link:
    x: -0.9562575721740723
    y: 0
    z: -0.113960205078125
    roll: 3.1282695000749925
    pitch: 3.1208899624664217
    yaw: 0.033137436884694976
  gnss_link:
    x: -1.1
    y: 0.15
    z: -1.5
    roll: 0.0
    pitch: 0.0
    yaw: -0.01
  camera0/camera_link:
    x: 1.7772341598898966
    y: 0.08209910228430033
    z: -1.1495020771593112
    roll: 1.5537968151945905
    pitch: 3.129112673919762
    yaw: 1.5762204348033229
  camera1/camera_link:
    x: 1.771277081309772
    y: -0.0388425260318721
    z: -1.0835366799518997
    roll: -1.5850062683272015
    pitch: 0.0082178877809234
    yaw: -1.546187159801762
  camera2/camera_link:
    x: -1.8767780753306706
    y: 0.067886919514624
    z: -1.2615388561051393
    roll: -1.5840938170277523
    pitch: -0.0007132481607602143
    yaw: 1.5808704793284738
  camera3/camera_link:
    x: 1.0653451910364133
    y: 1.0253316078309096
    z: -0.4419103164063101
    roll: -1.9129981268407064
    pitch: -0.033981646131042
    yaw: 0.8654299734762234
  camera4/camera_link:
    x: 1.3273211960016882
    y: -0.8254246676980426
    z: -0.391956031795005
    roll: -1.8857426118347849
    pitch: 0.0977858637771105
    yaw: 2.230997357635011
  camera5/camera_link:
    x: -1.143142462204828
    y: 0.8185711925429973
    z: -0.5987013275941906
    roll: 1.314998466374641
    pitch: -3.147105906589627
    yaw: 2.341021809293083
  camera6/camera_link:
    x: -1.1357019907885846
    y: -0.9288389577265109
    z: -0.6129262909315285
    roll: 1.3224408484189494
    pitch: -3.108762888594924
    yaw: 0.8923555358179915
  camera7/camera_link:
    x: 0.708
    y: 1.053
    z: 1.479
    roll: -1.553
    pitch: 0.063
    yaw: -1.584
