board_height: 13
board_width: 17
camera_name: test_camera
image_width: 3840
image_height: 2160
camera_matrix:
  rows: 3
  cols: 3
  dt: d
  data:
  - 1906.1237935137
  - 0.0
  - 1918.7952806578
  - 0.0
  - 1906.2847357867
  - 1077.3096966307
  - 0.0
  - 0.0
  - 1.0
distortion_model: plumb_bob
distortion_coefficients:
  rows: 14
  cols: 1
  dt: d
  data:
  - 2.2519708722
  - 0.550838615
  - 0.0001017026
  - 1.00944e-05
  - 0.0054125879
  - 2.6203759557
  - 1.258541721
  - 0.0719015792
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
rectification_matrix:
  rows: 3
  cols: 3
  data:
  - 1906.1237935137
  - 0.0
  - 1918.7952806578
  - 0.0
  - 1906.2847357867
  - 1077.3096966307
  - 0.0
  - 0.0
  - 1.0
projection_matrix:
  rows: 3
  cols: 4
  data:
  - 1906.1237935137
  - 0.0
  - 1918.7952806578
  - 0.0
  - 0.0
  - 1906.2847357867
  - 1077.3096966307
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
square_size: 50.0
flags: 16385
