board_height: 13
board_width: 17
camera_name: test_camera
image_width: 1920
image_height: 1080
camera_matrix:
  rows: 3
  cols: 3
  dt: d
  data:
  - 1016.1716440779
  - 0.0
  - 958.7588509589
  - 0.0
  - 1015.8741782795
  - 541.8091195657
  - 0.0
  - 0.0
  - 1.0
distortion_model: plumb_bob
distortion_coefficients:
  rows: 14
  cols: 1
  dt: d
  data:
  - 0.356405466
  - -0.1301642406
  - 2.87532e-05
  - -2.3627e-06
  - -0.0086708516
  - 0.7534161876
  - -0.0884908678
  - -0.0471387047
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
rectification_matrix:
  rows: 3
  cols: 3
  data:
  - 1016.1716440779
  - 0.0
  - 958.7588509589
  - 0.0
  - 1015.8741782795
  - 541.8091195657
  - 0.0
  - 0.0
  - 1.0
projection_matrix:
  rows: 3
  cols: 4
  data:
  - 1016.1716440779
  - 0.0
  - 958.7588509589
  - 0.0
  - 0.0
  - 1015.8741782795
  - 541.8091195657
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
square_size: 50.0
flags: 16385
