name: ""
encoder_pixfmt: 0  # H264,H265,VP8,VP9,AV1
raw_pixfmt: 0
is_semiplanar: false
bit_depth: 0
in_width: 1920
in_height: 1080
out_width: 1920
out_height: 1080
bitrate: 0
fps_n: 0
fps_d: 0
enable_initQP: false
IinitQP: 0
PinitQP: 0
BinitQP: 0
profile: 0
level: 0
enableLossless: false
enable_ratecontrol: false
enable_ratecontrol: false
peak_bitrate: 0
disable_amp: false
poc_type: 0
idr_interval: 0
slice_length: 0
enable_slice_level_encode: false
chroma_format_idc: 0
virtual_buffer_size: 0
slice_intrarefresh_interval: 0
insert_sps_pps_at_idr: true
disable_cabac: false
sar_width: 0
sar_height: 0
insert_vui: false
enable_extended_colorformat: false
insert_aud: false
alliframes: true
num_b_frames: 0
nMinQpI: 0
nMaxQpI: 0
nMinQpP: 0
nMaxQpP: 0
nMinQpB: 0
nMaxQpB: 0
sMaxQp: 0
max_perf: 0
dump_mv: false
bnoIframe: false
iframe_interval: 0
enableROI: false
enableGDR: false
bReconCrc: false
externalRPS: false
copy_timestamp: false
num_reference_frames: 0
externalRCHints: false
enable_av1ssimrdo: 0
disable_av1cdfupdate: 0
bGapsInFrameNumAllowed: false
nH264FrameNumBits: 0
nH265PocLsbBits: 0
enable_av1tile: false
log2_num_av1cols: 0
log2_num_av1rows: 0
output_plane_number: 10
capture_plane_number: 6