map:
  lidar_fl_base_link:
    x: -0.916866
    y: 1.91996
    z: 1.62635
    roll: 3.11293
    pitch: -0.0081588699999999
    yaw: 0.9553320000000002
  lidar_fr_base_link:
    x: -0.889256
    y: 0.29951
    z: 1.62226
    roll: -3.110506853589793
    pitch: -0.012162653589793
    yaw: -0.9167326535897932
  lidar_ft_base_link:
    x: -1.08236
    y: 1.07502
    z: 1.80022
    roll: -0.0024126535897932
    pitch: -0.0436126535897929
    yaw: -0.0111826535897933
  lidar_rt_base_link:
    x: -2.55881
    y: 1.08056
    z: 1.65835
    roll: 0.0119626535897931
    pitch: 0.0085526535897935
    yaw: -3.1007906535897933
  lidar_rear_base_link:
    x: -3.68615
    y: 1.05854
    z: 0.386446
    roll: 0.0100126535897932
    pitch: 0.0043226535897933
    yaw: -3.1313532535897934
