sensor_kit_base_link:
  lidar_fl_base_link:
    x: 1.1249421160358644
    y: 0.8934055566860767
    z: -0.4484982863297608
    roll: -3.135928690457725
    pitch: -0.012965987882825145
    yaw: 1.1365750414117932
  lidar_fr_base_link:
    x: 1.1611294806798593
    y: -0.8817487633299748
    z: -0.4821921918067185
    roll: 0.006155139595941749
    pitch: 3.1285480929847043
    yaw: 2.040937681157648
  lidar_ft_base_link:
    x: 0.8806398426774772
    y: 0.009999999299105796
    z: -0.08343785072326691
    roll: 0.013525612196624973
    pitch: 0.013851385130191242
    yaw: 0.01151549695348783
  lidar_rear_base_link:
    x: -1.9595356818869363
    y: -0.026865243459528607
    z: -1.5161449950698445
    roll: -0.016084272699686913
    pitch: -3.078145581475947
    yaw: 0.02312661046044217
  lidar_rt_base_link:
    x: -0.9217882649130553
    y: -0.0197440044156431
    z: -0.0028000544525950133
    roll: 3.127690869025555
    pitch: 3.117051222617487
    yaw: 0.03776604633384664
  gnss_link:
    x: -1.1
    y: 0.15
    z: -1.5
    roll: 0.0
    pitch: 0.0
    yaw: -0.01
  camera0/camera_link:
    x: 0.9230866333700941
    y: -0.0842383138711961
    z: 0.4735379562936071
    roll: -1.5309821207762995
    pitch: -0.0047230708657444165
    yaw: -1.6373760384774567
  camera1/camera_link:
    x: -0.09248376769610439
    y: -1.159167159786908
    z: -1.799885658539627
    roll: 1.308821464753083
    pitch: -1.533069688718875
    yaw: 0.25227949260398463
  camera2/camera_link:
    x: 0.03476846532601319
    y: -1.2190681742197698
    z: -1.847820543840398
    roll: -0.6412721860890535
    pitch: 1.5405264882148721
    yaw: -2.208520560655586
  camera3/camera_link:
    x: 1.0166803675862521
    y: 0.9523997499762583
    z: -0.44682014709151563
    roll: -1.5741233021754415
    pitch: -0.015286878023428816
    yaw: 0.8867194880679327
  camera4/camera_link:
    x: 1.3655306317891982
    y: -0.5473086941565232
    z: 0.00641466818742753
    roll: -2.010234054547943
    pitch: 0.7700471147260113
    yaw: 2.831733250672076
  camera5/camera_link:
    x: 1.3880583177242583
    y: -0.6149461279263665
    z: -0.04386705192193219
    roll: 1.9672045462126464
    pitch: -0.7565589339153245
    yaw: -0.2894686146285888
  camera6/camera_link:
    x: -1.4208573608314297
    y: -0.5499018446298825
    z: 0.031233772964919915
    roll: -2.0218885637384676
    pitch: -0.7959648637083147
    yaw: -2.816594709515074
  camera7/camera_link:
    x: 0.708
    y: 1.053
    z: 1.479
    roll: -1.553
    pitch: 0.063
    yaw: -1.584
