/**:
    ros__parameters:
        feature_extract_enable: false
        point_filter_num: 1
        max_iteration: 5
        filter_size_surf: 0.1
        filter_size_map: 0.1
        cube_side_length: 1000.0
        runtime_pos_log_enable: false
        map_file_path: "/home/ipc/pix/calibration_new/calib_data"

        common:
            lid_topic:  "/sensing/lidar/corrected/rear_top/points"
            # lid_topic:  "/sensing/lidar/concatenated/pointcloud"
            imu_topic:  "/sensing/imu/imu_data"
            time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
            time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                        # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0
            #toSensor_kit_base_link: [0.86257194519042968, 0.0, -0.083437850723266913, 0.014833389282226562, 0.026974668081222321, -0.0029244125951245342]  # [x,y,z,roll,pitch,yaw] from <lidar_base_link> to sensor_kit_base_link, in unit: meter and radian 
            
            toSensor_kit_base_link: [-0.95625757217407226, 0.0, -0.113960205078125, 3.1282695000749925, 3.1208899624664217, 0.033137436884694976]  # [x,y,z,roll,pitch,yaw] from <lidar_base_link> to sensor_kit_base_link, in unit: meter and radian re_top

        preprocess:
            lidar_type: 4                # 1 for RoboSense LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 4 for any other pointcloud input (pre-undistorted)
            scan_line: 1                 # For solid-state LiDAR: use 1; For traditional multi-line LiDAR: use actual line count (16/32/64/128)
            scan_rate: 10                # only need to be set for robosense, unit: Hz,
            timestamp_unit: 3            # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
            enable_undistort: false      # true: enable point cloud undistortion; false: assume input point cloud is already undistorted
            blind: 2.0

        mapping:
            acc_cov: 0.1
            gyr_cov: 0.1
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            fov_degree:    360.0
            det_range:     100.0
            extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic,
            extrinsic_T: [0.0, 0.0, 0.0]  # [x,y,z] from lidar to <base_link>, in unit: meter
            extrinsic_R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]

        publish:
            path_en:  false
            scan_publish_en:  true       # false: close all the point cloud output
            dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
            scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame
            map_en: true                 # 启用地图发布来累积点云用于保存

        pcd_save:
            pcd_save_en: true
            interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                        # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
