
video_device: "/dev/video3"
framerate: 10.0
io_method: "dma"
frame_id: "camera3/camera_link"
pixel_format: "yuyv2bgra"     # yuyv输出原始提图像用于标定，yuyv2bgra输出去畸变的bgra用于感知
# pixel_format: "uyvy"  
# pixel_format: "yuyv"  
av_device_format: "YUV422P"
is_distortion_correction: true
resize: 1
image_width: 1920
image_height: 1080
camera_name: "test_camera"
camera_info_url: file://${ROS_HOME}/../pix/parameter/sensor_kit/robobus_sensor_kit_description/intrinsic_parameters/camera3_params.yaml
brightness: -1
contrast: -1
saturation: -1
sharpness: -1
gain: -1
auto_white_balance: true
white_balance: 4000
autoexposure: true
exposure: 100
autofocus: false
focus: -1


# 不管去不去畸变，都要颜色空间转换
