image_width: 1920
image_height: 1080
camera_name: camera_top_6mm
camera_matrix:
   rows: 3
   cols: 3
   dt: d
   data: [ 1.9291795644867173e+03, 0., 9.8725018964567857e+02, 0.,
       1.9292844741669578e+03, 4.9887993461486900e+02, 0., 0., 1. ]
distortion_model: plumb_bob
distortion_coefficients:
   rows: 14
   cols: 1
   dt: d
   data: [ 2.4357112052337921e+00, 7.4384136540884171e+01,
       -8.7417505413810712e-04, 4.8721301869016905e-04,
       1.1479957026925401e+01, 3.0021407065085848e+00,
       7.5397046745680058e+01, 5.3578054425139889e+01, 0., 0., 0., 0.,
       0., 0. ]
projection_matrix:
  rows: 3
  cols: 4
  data: [1622.13934, 0.0, 956.59506, 0.0, 0.0, 1842.68983, 476.63579, 0.0, 0.0, 0.0,
    1.0, 0.0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]