map:
  lidar_fl_base_link:
    x: 0.104882
    y: 1.89124
    z: 1.80449
    roll: 3.11251
    pitch: -0.0701357
    yaw: 1.1748900000000002
  lidar_fr_base_link:
    x: 0.176862
    y: 0.115889
    z: 1.77165
    roll: -3.118701053589793
    pitch: -0.0054026535897931
    yaw: -1.0697626535897933
  lidar_ft_base_link:
    x: -0.153075
    y: 0.990042
    z: 2.28392
    roll: 0.00966392
    pitch: -0.0007292189999999
    yaw: 0.03172
  lidar_rt_base_link:
    x: -1.90267
    y: 0.903456
    z: 2.12463
    roll: -0.0011526535897933
    pitch: 0.0545226535897931
    yaw: -3.090926353589793
  lidar_rear_base_link:
    x: -2.89721
    y: 0.862689
    z: 0.649838
    roll: 3.117791853589793
    pitch: -0.0144926535897931
    yaw: -3.1026727535897933
