sensor_kit_base_link:
  lidar_fl_base_link:
    x: 1.1249421160358644
    y: 0.89340555668607669
    z: -0.4484982863297608
    roll: -3.135928690457725
    pitch: -0.012965987882825145
    yaw: 1.1365750414117932
  lidar_fr_base_link:
    x: 1.1611294806798593
    y: -0.88174876332997476
    z: -0.48219219180671852
    roll: 0.0061551395959417486
    pitch: 3.1285480929847043
    yaw: 2.0409376811576481
  lidar_ft_base_link:
    x: 0.88063984267747719
    y: 0.0099999992991057964
    z: -0.083437850723266913
    roll: 0.013525612196624973
    pitch: 0.013851385130191242
    yaw: 0.01151549695348783
  lidar_rear_base_link:
    x: -1.9595356818869363
    y: -0.026865243459528607
    z: -1.5161449950698445
    roll: -0.016084272699686913
    pitch: -3.0781455814759471
    yaw: 0.023126610460442169
  lidar_rt_base_link:
    x: -0.92178826491305532
    y: -0.019744004415643099
    z: -0.0028000544525950133
    roll: 3.1276908690255549
    pitch: 3.1170512226174871
    yaw: 0.037766046333846642
  gnss_link:
    x: -1.10
    y: 0.15
    z: -1.50
    roll: 0.0
    pitch: 0.0
    yaw: -0.01
  camera0/camera_link:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  camera1/camera_link:
    x: 1.8251573905670837
    y: 0.023255899370355448
    z: -1.0271999640780964
    roll: -1.5401845097338864
    pitch: 0.030715168567001294
    yaw: -1.4950916069207394
  camera2/camera_link:
    x: -1.7840533790619635
    y: -0.13155200595526398
    z: -1.1084684135451783
    roll: -1.5654257357303809
    pitch: 0.0010341249291464462
    yaw: 1.5830820445478977
  camera3/camera_link:
    x: -1.3502929172369615
    y: -0.57702558577664265
    z: 0.027987580414195357
    roll: 2.0304051730200765
    pitch: 0.82533946202765174
    yaw: 0.35655653672563076
  camera4/camera_link:
    x: 1.1318118813811513
    y: -0.81090303301710065
    z: -0.53772244778912459
    roll: -1.9070592595943263
    pitch: -0.012722370949975748
    yaw: 2.2214938627304415
  camera5/camera_link:
    x: -1.1315721500660501
    y: 0.84791375947442105
    z: -0.53192688889900464
    roll: -1.8295069595800952
    pitch: -0.0044572750525861959
    yaw: -0.98558064155695335
  camera6/camera_link:
    x: -1.0672411099226355
    y: -0.92154117167628269
    z: -0.51884786514238057
    roll: -1.8852997166514518
    pitch: 0.060646034060041654
    yaw: -2.2744039871212767
  camera7/camera_link:
    x: 0.708
    y: 1.053
    z: 1.479
    roll: -1.553
    pitch: 0.063
    yaw: -1.584